language: ruby
rvm:
  - 1.9.3
  - 2.0.0
    #- rbx-2.2.1 # broken. Gives  no such file to load -- singleton (LoadError)
  - jruby-19mode
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.0.gemfile
